version: '3.1'

services:
    db:
        container_name: nus_postgres
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=user_management
            - POSTGRES_USER=nest
            - POSTGRES_PASSWORD=password
        ports:
            - 5431:5432
